/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T02:28:53.829742327Z[GMT]
 * <br>
*  The generated test suite contains 35 tests
 * <br>
*  Covered targets: 144
 * <br>
*  Used time: 0h 1m 48s
 * <br>
*  Needed budget for current results: 74%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_location_user_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/countries
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnCountriesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/countries'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/countries")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/state-or-provinces
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnBackofficeState_or_provincesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/state-or-provinces'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/countries
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnCountriesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/countries")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/state-or-provinces
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnBackofficeState_or_provincesWithQueryParam() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces?countryId=405")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/backoffice/countries
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnCountriesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"50lNLJ\", " + 
                    " \"code2\": \"hIc\", " + 
                    " \"name\": \"p\", " + 
                    " \"code3\": \"gw\", " + 
                    " \"isShippingEnabled\": true, " + 
                    " \"isCityEnabled\": true " + 
                    " } ")
                .post(baseUrlOfSut + "/location/backoffice/countries")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/backoffice/state-or-provinces
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnState_or_provincesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"snOyU3olN\", " + 
                    " \"type\": \"CpOLKBqZfK6\", " + 
                    " \"countryId\": 184 " + 
                    " } ")
                .post(baseUrlOfSut + "/location/backoffice/state-or-provinces")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/storefront/addresses
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnAddressesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"contactName\": \"tzcymQi\", " + 
                    " \"phone\": \"fSlwPRJMkOi\", " + 
                    " \"addressLine1\": \"kYib\", " + 
                    " \"addressLine2\": \"7F3_nzfUo\", " + 
                    " \"zipCode\": \"nG\", " + 
                    " \"districtId\": 1757895013, " + 
                    " \"stateOrProvinceId\": 704, " + 
                    " \"countryId\": 550 " + 
                    " } ")
                .post(baseUrlOfSut + "/location/storefront/addresses")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/backoffice/countries
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_postOnCountriesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"XgnVvEfG1iTdt\", " + 
                    " \"code2\": \"2W\", " + 
                    " \"name\": \"LQhhNL4CGfXMDLU\", " + 
                    " \"code3\": \"em\", " + 
                    " \"isShippingEnabled\": true, " + 
                    " \"isCityEnabled\": false, " + 
                    " \"isZipCodeEnabled\": true " + 
                    " } ")
                .post(baseUrlOfSut + "/location/backoffice/countries")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/countries"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/backoffice/state-or-provinces
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_postOnState_or_provincesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"countryId\": 719 " + 
                    " } ")
                .post(baseUrlOfSut + "/location/backoffice/state-or-provinces")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/state-or-provinces"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/location/storefront/addresses
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_postOnAddressesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"phone\": \"YeU\", " + 
                    " \"addressLine1\": \"_fMfDt62Fm1Tw\", " + 
                    " \"districtId\": 265, " + 
                    " \"stateOrProvinceId\": 709, " + 
                    " \"countryId\": 20 " + 
                    " } ")
                .post(baseUrlOfSut + "/location/storefront/addresses")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/storefront/addresses"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/countries/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnCountriesPagingWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/countries/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/countries/paging?" + 
                    "pageNo=1412352818&" + 
                    "pageSize=961")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/district/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnDistrictReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/district/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/district/-1116518021")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/state-or-provinces/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/state-or-provinces/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/paging?" + 
                    "pageSize=656&" + 
                    "countryId=8746583612008399642")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/state-or-provinces/state-country-names
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnState_country_namesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/state-or-provinces/state-country-names'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/state-country-names?stateOrProvinceIds=491")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_getOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/countries/-2024476866")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/796")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/countries/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnCountriesPagingWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/countries/paging?pageSize=972541395")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/district/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnDistrictReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/district/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/district/395")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/state-or-provinces/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/paging?" + 
                    "pageNo=0&" + 
                    "pageSize=882")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/state-or-provinces/state-country-names
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_getOnState_country_namesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/state-country-names'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/state-country-names?stateOrProvinceIds=22&stateOrProvinceIds=241&stateOrProvinceIds=-581022166&stateOrProvinceIds=588&stateOrProvinceIds=435")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_getOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/countries/806")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_getOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/backoffice/state-or-provinces/3375905140250887203")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"-878476724\", " + 
                    " \"code2\": \"39\", " + 
                    " \"name\": \"ExnpNtz7uMsLlYcC\", " + 
                    " \"code3\": \"pL\", " + 
                    " \"isBillingEnabled\": true, " + 
                    " \"isCityEnabled\": false " + 
                    " } ")
                .put(baseUrlOfSut + "/location/backoffice/countries/-878476724")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_putOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"code\": \"Uf\", " + 
                    " \"type\": \"K\", " + 
                    " \"countryId\": 968 " + 
                    " } ")
                .put(baseUrlOfSut + "/location/backoffice/state-or-provinces/-696182791")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/storefront/addresses/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_putOnAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"phone\": \"owliQao_1k6he\", " + 
                    " \"zipCode\": \"\", " + 
                    " \"districtId\": 559, " + 
                    " \"stateOrProvinceId\": 1474524560, " + 
                    " \"countryId\": 43 " + 
                    " } ")
                .put(baseUrlOfSut + "/location/storefront/addresses/48")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_putOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"310\", " + 
                    " \"code2\": \"z\", " + 
                    " \"name\": \"rmh3qWPjM\", " + 
                    " \"code3\": \"uff\", " + 
                    " \"isBillingEnabled\": false, " + 
                    " \"isShippingEnabled\": true, " + 
                    " \"isCityEnabled\": false, " + 
                    " \"isZipCodeEnabled\": true, " + 
                    " \"isDistrictEnabled\": true " + 
                    " } ")
                .put(baseUrlOfSut + "/location/backoffice/countries/310")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/countries/310"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_26_putOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"J\" " + 
                    " } ")
                .put(baseUrlOfSut + "/location/backoffice/state-or-provinces/646")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/state-or-provinces/646"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/location/storefront/addresses/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_27_putOnAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"phone\": \"i6TQgUoS6vmWmH\", " + 
                    " \"addressLine2\": \"xqjBzLToVNqPg\", " + 
                    " \"districtId\": -2024727576, " + 
                    " \"stateOrProvinceId\": 595, " + 
                    " \"countryId\": 75 " + 
                    " } ")
                .put(baseUrlOfSut + "/location/storefront/addresses/1024532962")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/storefront/addresses/1024532962"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_28_deleteOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .delete(baseUrlOfSut + "/location/backoffice/countries/950")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_29_deleteOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .delete(baseUrlOfSut + "/location/backoffice/state-or-provinces/467")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/storefront/addresses/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_30_deleteOnAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .delete(baseUrlOfSut + "/location/storefront/addresses/910")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/backoffice/countries/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_31_deleteOnCountriReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/countries/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/location/backoffice/countries/186")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/countries/186"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/backoffice/state-or-provinces/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_32_deleteOnState_or_provincReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/state-or-provinces/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/location/backoffice/state-or-provinces/554")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/backoffice/state-or-provinces/554"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/location/storefront/addresses/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_33_deleteOnAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/addresses/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/location/storefront/addresses/558")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/location/storefront/addresses/558"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/location/storefront/addresses/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_34_getOnAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/storefront/addresses/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSclRUNWtBOHhIS3N0YWFSMmh1YTRpT0RpcFE4ek9pcjFrNGZOM3RxNFNVIn0.eyJleHAiOjE3Nzc4NTE4MTUsImlhdCI6MTc3Nzg0ODIxNSwianRpIjoiZTM2NzM0YzAtNWI0ZS00NjEyLWI2NGItNDE1YzY0YzQwNGNlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwMTEzZmQyNy1hMDllLTQ3MjItYjFlNS01MDA3ZjU4ZjUyODgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc5Nzg2MGJjLWY5ZDItNDY1MS05MGQ3LWIxMzZkN2VmOGM0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.MPhwctBIb64TKsK0SCXwzvrL2hB7g0Kn7iuK5aWmWJyyv2Xe6ddq6fbGJiXQmUxnNwmOPuSx-YTHj8Zw8SFCD--V7Wppy0xRsFhVK0abJa3-1QWqwCPX6CScfI5sqYnUXWaNwSnyWBV0UpGVGbsRvON47PkEHcX4EvYZQSxlyZ2VR26iLpK-6rrnl8cRiqmK5AogfmMNoU_usW9DCu8muLlGgQABm0jtSWg6kXT5vj2L6p1_3PmHhVFMdCiUrOqHgPZfAAd-L3jqHzW3PS6nwXZ9npao9hnvv1yRGWYYTr2Zgafw0z5CuxiwKv4NVtI36AA9I0R0SBnzMalcDA3L2Q") // Fixed Headers
                .get(baseUrlOfSut + "/location/storefront/addresses/748")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("The address 748 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
