/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T17:58:55.077792203Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 12
 * <br>
*  Used time: 0h 1m 47s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
*/
public class EvoMaster_promotion_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/promotion/storefront/promotions/updateUsage
    */
    @Test @Timeout(60)
    public void test_0_postOnUpdateUsageReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU0OTg1MjUsImlhdCI6MTc3NTQ5ODIyNSwianRpIjoiMjgxYWM3NDMtYTgyOC00M2VhLWFkMzctNjc3ZWRhODE2YjllIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZlZDU0MjNmLTQ1N2ItNDZkYy05NjdlLWJjOTFlYmU0ZjUxYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.XDtE02lhaikoR_3JHUbEwCuY6OY6wFbKM5-TPr7ampHW_outvf3v0FN8Wl3y3n5166YvGU-eB-XIzQVE3Po-0-3V5DrTiTv1w516nP2vRjPYwta27r7laRUsk2Sh9Th_kgZ_D59nAZTRKteitXufGVA4k8t2sRHY-vxK2RG52iFXvfM5UTJW5XZs_JoEx3HzTW1w2KGXpOIPW5cRiXBAc3o45UuyYREP90rUKLxxQfz4uYijBw9aEFezPLK6PT7CHqp7J8TiybuQ7hS5NawI9RHkYtgKFmSFUaoOp5W0BXwolZgVhoVaz--FVWl0u49GbPFQcmV_1-A7ZXmKU5hONw") // Fixed Headers
                .contentType("application/json")
                .body(" [] ")
                .post(baseUrlOfSut + "/promotion/storefront/promotions/updateUsage")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/promotion/backoffice/promotions/{promotionId}
    */
    @Test @Timeout(60)
    public void test_1_deleteOnPromotReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU0OTg1MjUsImlhdCI6MTc3NTQ5ODIyNSwianRpIjoiMjgxYWM3NDMtYTgyOC00M2VhLWFkMzctNjc3ZWRhODE2YjllIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZlZDU0MjNmLTQ1N2ItNDZkYy05NjdlLWJjOTFlYmU0ZjUxYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.XDtE02lhaikoR_3JHUbEwCuY6OY6wFbKM5-TPr7ampHW_outvf3v0FN8Wl3y3n5166YvGU-eB-XIzQVE3Po-0-3V5DrTiTv1w516nP2vRjPYwta27r7laRUsk2Sh9Th_kgZ_D59nAZTRKteitXufGVA4k8t2sRHY-vxK2RG52iFXvfM5UTJW5XZs_JoEx3HzTW1w2KGXpOIPW5cRiXBAc3o45UuyYREP90rUKLxxQfz4uYijBw9aEFezPLK6PT7CHqp7J8TiybuQ7hS5NawI9RHkYtgKFmSFUaoOp5W0BXwolZgVhoVaz--FVWl0u49GbPFQcmV_1-A7ZXmKU5hONw") // Fixed Headers
                .delete(baseUrlOfSut + "/promotion/backoffice/promotions/635")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
