/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-09T00:18:02.357447117Z[GMT]
 * <br>
*  The generated test suite contains 7 tests
 * <br>
*  Covered targets: 26
 * <br>
*  Used time: 0h 1m 28s
 * <br>
*  Needed budget for current results: 67%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_media_admin_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/media/medias
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnMediasShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. null.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 500 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTU2OTIsImlhdCI6MTc3MzAxNTM5MiwianRpIjoiMzVjODM4NGMtYTZmOC00ZDQ5LWFhNDMtMjlkMmRiOGMwNWMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg4YTdlZDg0LTBkMDEtNDdlNi1hYzdkLTQ2YjdkZjZlY2NmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XH2bGXToLZiUozH1e1F0oO0kiu4ksBmHAvdJpKua6vlmZGeexLHi2GkXvjDZJnQRHz6AybxW7kV_-jJTIcRBqTv3Bst4--7hm59hcV74NYEMsq4yqG5xMfvNP9P-R1yGT6mRkhrbd5FOC1ZB9-VCy-6bdnOPlsAL-tmMTJ5gKfbS5gHXKv4eLbKA9fErQSz-dK5JVmsf8whmcuN9vG0mXg_QBYH_OReHYR40kLliJcn9A188ZO_CNxq5AgrDaFClXvM6mfxtPYan1UCrkrJG3siBcx1Cmq_aq-c47HOwi2vk-Mb7jlN3oqaZsenHIFuFF7OYB4pO7SheW1NGCHPG-Q") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("Content-Type 'application/x-www-form-urlencoded' is not supported"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/medias'.
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("caption=2p1opB2uGNj&multipartFile=TuYJwbXO9j06&fileNameOverride=")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTU2OTIsImlhdCI6MTc3MzAxNTM5MiwianRpIjoiMzVjODM4NGMtYTZmOC00ZDQ5LWFhNDMtMjlkMmRiOGMwNWMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg4YTdlZDg0LTBkMDEtNDdlNi1hYzdkLTQ2YjdkZjZlY2NmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XH2bGXToLZiUozH1e1F0oO0kiu4ksBmHAvdJpKua6vlmZGeexLHi2GkXvjDZJnQRHz6AybxW7kV_-jJTIcRBqTv3Bst4--7hm59hcV74NYEMsq4yqG5xMfvNP9P-R1yGT6mRkhrbd5FOC1ZB9-VCy-6bdnOPlsAL-tmMTJ5gKfbS5gHXKv4eLbKA9fErQSz-dK5JVmsf8whmcuN9vG0mXg_QBYH_OReHYR40kLliJcn9A188ZO_CNxq5AgrDaFClXvM6mfxtPYan1UCrkrJG3siBcx1Cmq_aq-c47HOwi2vk-Mb7jlN3oqaZsenHIFuFF7OYB4pO7SheW1NGCHPG-Q") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias?ids=177&ids=-492392809")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/media/medias/-401914847")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias/-401914847"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTU2OTIsImlhdCI6MTc3MzAxNTM5MiwianRpIjoiMzVjODM4NGMtYTZmOC00ZDQ5LWFhNDMtMjlkMmRiOGMwNWMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg4YTdlZDg0LTBkMDEtNDdlNi1hYzdkLTQ2YjdkZjZlY2NmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XH2bGXToLZiUozH1e1F0oO0kiu4ksBmHAvdJpKua6vlmZGeexLHi2GkXvjDZJnQRHz6AybxW7kV_-jJTIcRBqTv3Bst4--7hm59hcV74NYEMsq4yqG5xMfvNP9P-R1yGT6mRkhrbd5FOC1ZB9-VCy-6bdnOPlsAL-tmMTJ5gKfbS5gHXKv4eLbKA9fErQSz-dK5JVmsf8whmcuN9vG0mXg_QBYH_OReHYR40kLliJcn9A188ZO_CNxq5AgrDaFClXvM6mfxtPYan1UCrkrJG3siBcx1Cmq_aq-c47HOwi2vk-Mb7jlN3oqaZsenHIFuFF7OYB4pO7SheW1NGCHPG-Q") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias/159")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_getOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTU2OTIsImlhdCI6MTc3MzAxNTM5MiwianRpIjoiMzVjODM4NGMtYTZmOC00ZDQ5LWFhNDMtMjlkMmRiOGMwNWMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg4YTdlZDg0LTBkMDEtNDdlNi1hYzdkLTQ2YjdkZjZlY2NmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XH2bGXToLZiUozH1e1F0oO0kiu4ksBmHAvdJpKua6vlmZGeexLHi2GkXvjDZJnQRHz6AybxW7kV_-jJTIcRBqTv3Bst4--7hm59hcV74NYEMsq4yqG5xMfvNP9P-R1yGT6mRkhrbd5FOC1ZB9-VCy-6bdnOPlsAL-tmMTJ5gKfbS5gHXKv4eLbKA9fErQSz-dK5JVmsf8whmcuN9vG0mXg_QBYH_OReHYR40kLliJcn9A188ZO_CNxq5AgrDaFClXvM6mfxtPYan1UCrkrJG3siBcx1Cmq_aq-c47HOwi2vk-Mb7jlN3oqaZsenHIFuFF7OYB4pO7SheW1NGCHPG-Q") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias/-612365293301964972")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTU2OTIsImlhdCI6MTc3MzAxNTM5MiwianRpIjoiMzVjODM4NGMtYTZmOC00ZDQ5LWFhNDMtMjlkMmRiOGMwNWMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg4YTdlZDg0LTBkMDEtNDdlNi1hYzdkLTQ2YjdkZjZlY2NmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XH2bGXToLZiUozH1e1F0oO0kiu4ksBmHAvdJpKua6vlmZGeexLHi2GkXvjDZJnQRHz6AybxW7kV_-jJTIcRBqTv3Bst4--7hm59hcV74NYEMsq4yqG5xMfvNP9P-R1yGT6mRkhrbd5FOC1ZB9-VCy-6bdnOPlsAL-tmMTJ5gKfbS5gHXKv4eLbKA9fErQSz-dK5JVmsf8whmcuN9vG0mXg_QBYH_OReHYR40kLliJcn9A188ZO_CNxq5AgrDaFClXvM6mfxtPYan1UCrkrJG3siBcx1Cmq_aq-c47HOwi2vk-Mb7jlN3oqaZsenHIFuFF7OYB4pO7SheW1NGCHPG-Q") // Fixed Headers
                .delete(baseUrlOfSut + "/media/medias/191671670")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Media 191671670 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
