app:
  security:
    rules:
      - patterns: 
          - "/storefront/ratings/product/**/average-star"
        authenticated: true
      - patterns:
          - "/actuator/prometheus"
          - "/actuator/health/**"
          - "/swagger-ui"
          - "/swagger-ui/**"
          - "/error"
          - "/v3/api-docs/**"
        permit-all: true

      - patterns:
          - "/storefront/**"
        permit-all: true

      - patterns:
          - "/backoffice/**"
        roles:
          - "ADMIN"
