app:
  security:
    rules:
      - patterns: 
          - "/backoffice/categories/by-ids"
        roles: 
          - "SUPER-ADMIN"
      - patterns:
          - "/actuator/prometheus"
          - "/actuator/health/**"
          - "/swagger-ui"
          - "/swagger-ui/**"
          - "/error"
          - "/v3/api-docs/**"
        permit-all: true

      - patterns:
          - "/storefront/**"
        permit-all: true

      - patterns:
          - "/backoffice/**"
        roles:
          - "ADMIN"
