/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-09T00:57:58.852230342Z[GMT]
 * <br>
*  The generated test suite contains 9 tests
 * <br>
*  Covered targets: 52
 * <br>
*  Used time: 0h 1m 27s
 * <br>
*  Needed budget for current results: 93%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_rating_none_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "createdFrom=2081-11-10T17%3A31%3A56.281%2B10%3A51&" + 
                    "createdTo=1960-09-08T19%3A20%3A58-07%3A05&" + 
                    "pageSize=373")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=0XH4ZjY&" + 
                    "customerName=&" + 
                    "createdFrom=2015-04-22T-1%3A27%3A57Z&" + 
                    "createdTo=2014-07-31T14%3A07%3A38Z")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=rPQ1dzN&" + 
                    "customerName=&" + 
                    "message=1HDO&" + 
                    "createdTo=2072-08-10T01%3A16%3A08Z&" + 
                    "pageNo=349&" + 
                    "pageSize=786")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "customerName=h&" + 
                    "createdFrom=2070-13-21T13%3A39%3A21.604Z&" + 
                    "pageSize=693")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "customerName=&" + 
                    "message=1Li1lnBLL6K&" + 
                    "pageNo=0&" + 
                    "pageSize=826")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_getOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=WSEsBbXpNSI&" + 
                    "message=FXOlLD4BQmu&" + 
                    "createdFrom=2062-08-00T14%3A06%3A49-02%3A27&" + 
                    "pageNo=732&" + 
                    "pageSize=130")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/rating/storefront/ratings
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnRatingsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/storefront/ratings'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": 211, " + 
                    " \"productName\": \"junXB\" " + 
                    " } ")
                .post(baseUrlOfSut + "/rating/storefront/ratings")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/rating/storefront/ratings"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/rating/backoffice/ratings/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_deleteOnRateReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/ratings/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/rating/backoffice/ratings/19")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/rating/backoffice/ratings/19"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/rating/backoffice/ratings/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/ratings/latest/{count}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/backoffice/ratings/latest/66")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
