/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T22:01:09.979996671Z[GMT]
 * <br>
*  The generated test suite contains 28 tests
 * <br>
*  Covered targets: 137
 * <br>
*  Used time: 0h 1m 35s
 * <br>
*  Needed budget for current results: 90%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_user_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/order/storefront/checkouts
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnCheckoutsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"promotionCode\" : \"XlY\", " + 
                    " \"shipmentMethodId\" : \"35\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"productId\" : 379, " + 
                    " \"quantity\" : 750 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"XOK_\", " + 
                    " \"shipmentMethodId\" : \"kWZnTcJW24oR_Sq\", " + 
                    " \"paymentMethodId\" : \"goEMxBct\", " + 
                    " \"shippingAddressId\" : \"bAy1opLu5\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"description\" : \"QNI_qVD9VQ2tQ\" " + 
                    " }, { " + 
                    " \"description\" : \"YdHCtV\", " + 
                    " \"quantity\" : 992 " + 
                    " }, { " + 
                    " \"description\" : \"sLX__2EBBKK\" " + 
                    " }, { } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"sR93ci0pubHJ\", " + 
                    " \"email\" : \"9cJ\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"jc29QH0OOUg4q9V\", " + 
                    " \"phone\" : \"tGVtRU\", " + 
                    " \"addressLine1\" : \"UlsXy_Hd\", " + 
                    " \"city\" : \"Hqx\", " + 
                    " \"zipCode\" : \"oj8PVFvt0\", " + 
                    " \"districtId\" : 211, " + 
                    " \"districtName\" : \"Mpko2HU1\", " + 
                    " \"stateOrProvinceId\" : -547924460, " + 
                    " \"stateOrProvinceName\" : \"Lu\", " + 
                    " \"countryId\" : 797, " + 
                    " \"countryName\" : \"En\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"FaO\", " + 
                    " \"phone\" : \"DPJF_DnZq_\", " + 
                    " \"addressLine1\" : \"FW\", " + 
                    " \"addressLine2\" : \"k9\", " + 
                    " \"city\" : \"_q\", " + 
                    " \"zipCode\" : \"8ri0P5\", " + 
                    " \"districtId\" : 252, " + 
                    " \"districtName\" : \"gj\", " + 
                    " \"stateOrProvinceId\" : 785, " + 
                    " \"stateOrProvinceName\" : \"3toiPJRMEMc\", " + 
                    " \"countryId\" : 233, " + 
                    " \"countryName\" : \"qDOURhXSW2\" " + 
                    " }, " + 
                    " \"note\" : \"XGy2RvZsrXTOOgf\", " + 
                    " \"tax\" : 7.229285E8, " + 
                    " \"totalPrice\" : 8.809544177378327E8, " + 
                    " \"deliveryFee\" : -1.0854486723906462E9, " + 
                    " \"couponCode\" : \"sa99Fr\", " + 
                    " \"deliveryMethod\" : \"GRAB_EXPRESS\", " + 
                    " \"paymentMethod\" : \"COD\", " + 
                    " \"paymentStatus\" : \"EVOMASTER\", " + 
                    " \"orderItemPostVms\" : [ ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdTo=1996-04-05T21%3A52%3A12.129%2B06%3A31&" + 
                    "productName=&" + 
                    "email=YQ&" + 
                    "pageSize=10")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=2066-10-30T25%3A36%3A30.969-15%3A52&" + 
                    "orderStatus=SHIPPING&orderStatus=PENDING_PAYMENT&orderStatus=PENDING&orderStatus=COMPLETED&" + 
                    "email=N_nyPJOoglz3B&" + 
                    "billingCountry=ZabNUd")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1952-09-27T00%3A16%3A15.931Z&" + 
                    "productName=dkm5py2bQ&" + 
                    "orderStatus=REJECT&orderStatus=REJECT&" + 
                    "billingPhoneNumber=CPTlsH8ejUaY&" + 
                    "email=krf&" + 
                    "billingCountry=i2SM&" + 
                    "pageNo=473&" + 
                    "pageSize=418")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnBackofficeOrdersWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?billingPhoneNumber=wO")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "productName=baEiM&" + 
                    "orderStatus=REFUND&" + 
                    "email=0kD")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"m\", " + 
                    " \"promotionCode\" : \"zJ\", " + 
                    " \"shipmentMethodId\" : \"ZAGLow9QfjSXOLX\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"productId\" : 569 " + 
                    " }, { " + 
                    " \"productId\" : 213 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"NIT5\", " + 
                    " \"email\" : \"1MfiFddvgCCKac\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"7O1fclSuWkm\", " + 
                    " \"phone\" : \"gT2_os9BHaz\", " + 
                    " \"addressLine1\" : \"XUCAdwX2eTk\", " + 
                    " \"addressLine2\" : \"f5Gam9zDkfbCE\", " + 
                    " \"city\" : \"lqvHNVTk\", " + 
                    " \"zipCode\" : \"O69WzWBJGxI7\", " + 
                    " \"districtId\" : 723, " + 
                    " \"districtName\" : \"DjFDT\", " + 
                    " \"stateOrProvinceId\" : 594, " + 
                    " \"stateOrProvinceName\" : \"xWOaq1TfHFxU5WC\", " + 
                    " \"countryId\" : 751, " + 
                    " \"countryName\" : \"wFVoCgv_\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"prek7\", " + 
                    " \"phone\" : \"1_HX7CsiG\", " + 
                    " \"addressLine1\" : \"Dzc_WNuI\", " + 
                    " \"city\" : \"T8\", " + 
                    " \"zipCode\" : \"JDwk\", " + 
                    " \"districtId\" : 546, " + 
                    " \"districtName\" : \"aI\", " + 
                    " \"stateOrProvinceId\" : -1507237755990471974, " + 
                    " \"stateOrProvinceName\" : \"L\", " + 
                    " \"countryId\" : 810, " + 
                    " \"countryName\" : \"jEFqkzs5Fjb0tYuI\" " + 
                    " }, " + 
                    " \"tax\" : -3.4850736E8, " + 
                    " \"discount\" : 9.480423E7, " + 
                    " \"totalPrice\" : 8.978947189240155E8, " + 
                    " \"couponCode\" : \"\", " + 
                    " \"deliveryMethod\" : \"GRAB_EXPRESS\", " + 
                    " \"paymentMethod\" : \"EVOMASTER\", " + 
                    " \"paymentStatus\" : \"PENDING\", " + 
                    " \"orderItemPostVms\" : [ { " + 
                    " \"quantity\" : 517, " + 
                    " \"productPrice\" : -1.0339459657089103E9, " + 
                    " \"discountAmount\" : -5.57907558106982E8, " + 
                    " \"taxPercent\" : 3.32897141306665E8 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/checkouts/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_10_getOnStorefrontCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/checkouts/Ff8y70ZRV")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/Ff8y70ZRV"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_11_getOnOrdersCompletedWithQueryParamNegativeProductIdShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=-911824337")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/my-orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_12_getOnMy_ordersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=ayF_Ts_yPno04qd")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_13_getOnOrdersCompletedWithQueryParamShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=662")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_14_putOnCheckoutsStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/orders/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_15_putOnOrdersStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"orderId\" : 640, " + 
                    " \"orderStatus\" : \"Vjjw7mu\", " + 
                    " \"paymentId\" : -7997743519786774149 " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/-7587490412658859438")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/-1049200682")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/923")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"createdFrom\" : \"1924-11-22T09:05:41.340Z\", " + 
                    " \"warehouse\" : \"ITmN0ipuP\", " + 
                    " \"orderStatus\" : [ ], " + 
                    " \"billingPhoneNumber\" : \"wNbHohvScI2Vilq\", " + 
                    " \"email\" : \"kMjqsZw9R121YuV\", " + 
                    " \"billingCountry\" : \"1DVF1B6si\", " + 
                    " \"pageSize\" : 795 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"createdTo\" : \"2007-10-19T16:01:28.958Z\", " + 
                    " \"warehouse\" : \"zwMeeGl4uhC4p\", " + 
                    " \"productName\" : \"xI1JQggLfxykl\", " + 
                    " \"billingPhoneNumber\" : \"Zcd6\", " + 
                    " \"email\" : \"mUxBa\", " + 
                    " \"billingCountry\" : \"IyThcU\", " + 
                    " \"pageNo\" : 808, " + 
                    " \"pageSize\" : 730 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_putOnCheckoutsStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/orders/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnOrdersStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"orderStatus\" : \"hNrPt\", " + 
                    " \"paymentStatus\" : \"aLq56m\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/checkout/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_23_getOnOrdersCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/checkout/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/checkout/FI")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/checkout/FI"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_24_putOnPayment_methodShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/gF/payment-method")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/gF/payment-method"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/latest/{count}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/158")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/order/backoffice/orders/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_26_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/latest/{count}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTMwNzIsImlhdCI6MTc3NTUxMjc3MiwianRpIjoiYjJiOTk3Y2YtODMwMC00MTA4LWJhYmYtZDFhZTA3N2RhNjJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiYmRiYjAxLWVhMTYtNDUwYy1iYmY5LTdiN2U2ZTVlOGE4NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.lKJh89NukfqNcFjUSJI-ohk_DvsQGIMlqxvM8J2_nVe1XWHaR4xr3uf_XK09H8I0wip6vAUsoT0eLoGmc_9v5vrhqIy18_aaPvKjy91jRG6kzZ7hvi8hSoOJgWESxzZw67rcJkgYsuf7wdQD-85SZf4b9ZBox5Al5qqPeIaBz7ixaJKXYsTtEnmaTpe08znOj1237VMiP3OkGrTBEZ9lrkdUFgVELzbt1MgFGZXkm4yCmZudZ3PcbAMnE3yS3JmvdIVYEfYfK2IP6Gnc2jlXnVkaQ4t9T7gHC50xmt4bND5ZOlOkEjCAQ6gGn2po7deG2SsK-loL8yNgkzWsj-4DhA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/612")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_27_putOnPayment_methodReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"paymentMethodId\" : \"ReVlLE\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/e03eECu7gGlT/payment-method")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/e03eECu7gGlT/payment-method"));
    }


}
