/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T03:14:52.912396750Z[GMT]
 * <br>
*  The generated test suite contains 25 tests
 * <br>
*  Covered targets: 134
 * <br>
*  Used time: 0h 1m 49s
 * <br>
*  Needed budget for current results: 94%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_admin_only_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnOrdersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "productName=FCI&" + 
                    "billingCountry=OGhMaRWLCbTquqFF")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/order/storefront/orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_postOnOrdersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"M4ufLQ_\", " + 
                    " \"email\" : \"4WCCWAyhkrbZ\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"qpelxr7tdjwqR\", " + 
                    " \"phone\" : \"xANJza\", " + 
                    " \"addressLine1\" : \"AzCyLUE_nyA7\", " + 
                    " \"addressLine2\" : \"ns659Ax\", " + 
                    " \"city\" : \"9m2GkzZrh50\", " + 
                    " \"zipCode\" : \"GR7\", " + 
                    " \"districtId\" : 3783782843531928553, " + 
                    " \"districtName\" : \"EsdM4Pt\", " + 
                    " \"stateOrProvinceId\" : 2092216703, " + 
                    " \"stateOrProvinceName\" : \"GFlRQodh6\", " + 
                    " \"countryId\" : 589, " + 
                    " \"countryName\" : \"mgcvrCUjM6QlLu\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"cYzlFH\", " + 
                    " \"phone\" : \"yJmNnChIDGRejY\", " + 
                    " \"addressLine1\" : \"oMptYmDCtL\", " + 
                    " \"addressLine2\" : \"gvf_52q\", " + 
                    " \"city\" : \"QqTthaMwzhGWYi\", " + 
                    " \"zipCode\" : \"iinMBLk5ZCEpI0O\", " + 
                    " \"districtId\" : 995, " + 
                    " \"districtName\" : \"R_rXdSBD8wt7v\", " + 
                    " \"stateOrProvinceId\" : 114, " + 
                    " \"stateOrProvinceName\" : \"nqCezFdMYJE\", " + 
                    " \"countryId\" : 394, " + 
                    " \"countryName\" : \"sTzSDHCf\" " + 
                    " }, " + 
                    " \"note\" : \"gq\", " + 
                    " \"tax\" : 7.736085E8, " + 
                    " \"discount\" : -5.6451456E8, " + 
                    " \"numberItem\" : 972, " + 
                    " \"totalPrice\" : 4.206359487495645E8, " + 
                    " \"deliveryFee\" : -3.3305847942139125E8, " + 
                    " \"couponCode\" : \"6yBcR2zbCPlsK9Em\", " + 
                    " \"deliveryMethod\" : \"SHOPEE_EXPRESS\", " + 
                    " \"paymentMethod\" : \"COD\", " + 
                    " \"paymentStatus\" : \"COMPLETED\", " + 
                    " \"orderItemPostVms\" : [ ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1906-02-31T02%3A21%3A18Z&" + 
                    "orderStatus=PENDING_PAYMENT&orderStatus=ACCEPTED&" + 
                    "billingCountry=2PIC_J&" + 
                    "pageSize=68")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/backoffice/orders"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"CJS3M2Y0mHCit\", " + 
                    " \"note\" : \"\", " + 
                    " \"promotionCode\" : \"THm98\", " + 
                    " \"shippingAddressId\" : \"apBfTvx2NHoI\", " + 
                    " \"checkoutItemPostVms\" : [ { }, { " + 
                    " \"productId\" : -418847766483365739, " + 
                    " \"description\" : \"Z8d1k\", " + 
                    " \"quantity\" : 296 " + 
                    " }, { } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"9cH\", " + 
                    " \"email\" : \"95NnSEqR\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"0N38arkW6cA\", " + 
                    " \"phone\" : \"tIUaAVtc61tM\", " + 
                    " \"addressLine1\" : \"PTEHLPCuD3xwcli\", " + 
                    " \"addressLine2\" : \"ryjYfFM\", " + 
                    " \"city\" : \"77TZZ_2aF\", " + 
                    " \"zipCode\" : \"0md2\", " + 
                    " \"districtId\" : 507, " + 
                    " \"districtName\" : \"1_F\", " + 
                    " \"stateOrProvinceId\" : 948, " + 
                    " \"stateOrProvinceName\" : \"viAAeZ3QoYg3G\", " + 
                    " \"countryId\" : 599, " + 
                    " \"countryName\" : \"IeQBTjF77uKCKW1\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"Dc\", " + 
                    " \"phone\" : \"AKW4g6DgrV\", " + 
                    " \"addressLine1\" : \"MHNYNNKY\", " + 
                    " \"addressLine2\" : \"\", " + 
                    " \"city\" : \"5b8IaZDequIql0KY\", " + 
                    " \"zipCode\" : \"QLGPfbOBW0mtrKf1\", " + 
                    " \"districtId\" : 537, " + 
                    " \"districtName\" : \"1_YS4\", " + 
                    " \"stateOrProvinceId\" : 993, " + 
                    " \"stateOrProvinceName\" : \"qZteCZvQAitPuU\", " + 
                    " \"countryId\" : 757, " + 
                    " \"countryName\" : \"1wJNaXsIo1n\" " + 
                    " }, " + 
                    " \"tax\" : 4.3574464E8, " + 
                    " \"numberItem\" : 266, " + 
                    " \"totalPrice\" : 6.978902721532387E8, " + 
                    " \"deliveryFee\" : 6.256387239978489E8, " + 
                    " \"couponCode\" : \"a1QUuEKTb3fNvGD\", " + 
                    " \"deliveryMethod\" : \"EVOMASTER\", " + 
                    " \"paymentMethod\" : \"PAYPAL\", " + 
                    " \"paymentStatus\" : \"COMPLETED\", " + 
                    " \"orderItemPostVms\" : [ { " + 
                    " \"productName\" : \"3YUIN4bA99xEhFv_\", " + 
                    " \"taxAmount\" : 8.346326866267377E7, " + 
                    " \"taxPercent\" : -1.0673011389207722E8 " + 
                    " }, { " + 
                    " \"productName\" : \"vU9ouxH4bWWNagrH\", " + 
                    " \"quantity\" : 479, " + 
                    " \"productPrice\" : -9.066845253306628E8, " + 
                    " \"note\" : \"rlonBUgSEF\", " + 
                    " \"discountAmount\" : -5.750856241395721E8, " + 
                    " \"taxPercent\" : 5.269101046614869E7 " + 
                    " }, { " + 
                    " \"productName\" : \"zXz4pos\", " + 
                    " \"note\" : \"PetV_yZSntb\", " + 
                    " \"discountAmount\" : -6.986011409743172E7, " + 
                    " \"taxPercent\" : 8.991455798621873E8 " + 
                    " }, { " + 
                    " \"productId\" : 811, " + 
                    " \"quantity\" : 330, " + 
                    " \"note\" : \"vgW0gYohJmew\", " + 
                    " \"discountAmount\" : 1.1078699682868063E9 " + 
                    " }, { " + 
                    " \"productId\" : 386, " + 
                    " \"productPrice\" : 5.015290501392874E8, " + 
                    " \"taxAmount\" : -2.0780954972453928E8 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1934-12-12T07%3A08%3A37%2B09%3A55&" + 
                    "createdTo=2006-00-05T19%3A44%3A56%2B02%3A27&" + 
                    "productName=TPv1ho_Fa&" + 
                    "billingPhoneNumber=696rPp64n&" + 
                    "pageNo=428&" + 
                    "pageSize=273")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"productId\" : 233 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"T8OmYZSxqHlp\", " + 
                    " \"email\" : \"QB5I_2c7W7w1xh3\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"vBvTqQmtGq8pWS\", " + 
                    " \"phone\" : \"wvUT\", " + 
                    " \"addressLine1\" : \"GiWoVmVv6\", " + 
                    " \"addressLine2\" : \"\", " + 
                    " \"city\" : \"yB0EwGJoNIvSU8oh\", " + 
                    " \"zipCode\" : \"rY1p\", " + 
                    " \"districtId\" : -7540924881639949605, " + 
                    " \"districtName\" : \"p82\", " + 
                    " \"stateOrProvinceId\" : 4536016918650681414, " + 
                    " \"stateOrProvinceName\" : \"64Cubf4yWLuD7\", " + 
                    " \"countryId\" : 449, " + 
                    " \"countryName\" : \"a\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"flo\", " + 
                    " \"phone\" : \"pQpgzZgYEwSdThb\", " + 
                    " \"addressLine1\" : \"JPulfOJ\", " + 
                    " \"city\" : \"UDOCMbR9\", " + 
                    " \"zipCode\" : \"acDKe\", " + 
                    " \"districtId\" : 783, " + 
                    " \"districtName\" : \"wx0GzFdf9\", " + 
                    " \"stateOrProvinceId\" : -112513059, " + 
                    " \"stateOrProvinceName\" : \"scLJcu\", " + 
                    " \"countryId\" : 857, " + 
                    " \"countryName\" : \"LFaZ\" " + 
                    " }, " + 
                    " \"note\" : \"tMz1PUIp3eazFj7\", " + 
                    " \"tax\" : 8.849007E8, " + 
                    " \"discount\" : -1.3671776E9, " + 
                    " \"numberItem\" : 291, " + 
                    " \"totalPrice\" : 4.6255422975290515E7, " + 
                    " \"deliveryMethod\" : \"GRAB_EXPRESS\", " + 
                    " \"paymentMethod\" : \"BANKING\", " + 
                    " \"paymentStatus\" : \"COMPLETED\", " + 
                    " \"orderItemPostVms\" : [ { " + 
                    " \"productName\" : \"SS9GS0\", " + 
                    " \"productPrice\" : 3.0078180858206116E7, " + 
                    " \"note\" : \"ha_w\", " + 
                    " \"taxPercent\" : -1.60711863608314E8 " + 
                    " }, { " + 
                    " \"quantity\" : 297, " + 
                    " \"note\" : \"ArwUvaTH8\", " + 
                    " \"discountAmount\" : -2.6156752365140265E8, " + 
                    " \"taxAmount\" : -2.9340820978376776E8, " + 
                    " \"taxPercent\" : 1439535.1377330665 " + 
                    " }, { " + 
                    " \"productId\" : 425, " + 
                    " \"productName\" : \"uZ8ahJ_iay\", " + 
                    " \"note\" : \"Orp8aHlce5\", " + 
                    " \"discountAmount\" : 1.1720321170846157E9, " + 
                    " \"taxAmount\" : 4.336479171916772E8 " + 
                    " }, { " + 
                    " \"productId\" : 5152964179461514890, " + 
                    " \"productName\" : \"kM1Fckp9T4R\", " + 
                    " \"quantity\" : 717, " + 
                    " \"note\" : \"o3mb\" " + 
                    " }, { " + 
                    " \"productId\" : 737, " + 
                    " \"productPrice\" : 5.869272328294571E7, " + 
                    " \"taxAmount\" : 6.754925290948728E8, " + 
                    " \"taxPercent\" : -5.455997988784796E8 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_8_getOnOrderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/297")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders/297"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/checkouts/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_9_getOnStorefrontCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/checkouts/3ssJTcV")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/3ssJTcV"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_10_getOnCompletedShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=19")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/my-orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_11_getOnMy_ordersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=Rxmj1POjBSlYNOr")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/order/backoffice/orders/csv
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_12_postOnCsvShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"createdFrom\" : \"2023-09-28T12:01:12Z\", " + 
                    " \"warehouse\" : \"QDQ3BvfqRm8Y\", " + 
                    " \"productName\" : \"H6\", " + 
                    " \"orderStatus\" : [ \"REFUND\" ], " + 
                    " \"email\" : \"MVLQ\", " + 
                    " \"pageNo\" : 981, " + 
                    " \"pageSize\" : 811 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/orders/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_13_putOnOrdersStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"orderId\" : 134, " + 
                    " \"paymentStatus\" : \"Qd\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_14_putOnCheckoutsStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"G72oSnCLTocCi\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/order/storefront/orders/my-orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnMy_ordersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?" + 
                    "productName=cA&" + 
                    "orderStatus=EVOMASTER")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"createdFrom\" : \"1902-11-04T11:40:49.321-17:29\", " + 
                    " \"createdTo\" : \"2008-11-04T14:13:45.195Z\", " + 
                    " \"orderStatus\" : [ \"REJECT\", \"PAID\", \"COMPLETED\" ], " + 
                    " \"billingPhoneNumber\" : \"uA0Nv8Ys40\", " + 
                    " \"pageSize\" : 1 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/159")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"createdTo\" : \"2021-04-25T19:35:16.197-11:30\", " + 
                    " \"warehouse\" : \"ZWxosaEnm\", " + 
                    " \"orderStatus\" : [ \"REFUND\", \"CANCELLED\", \"SHIPPING\", \"REFUND\", \"CANCELLED\" ], " + 
                    " \"billingPhoneNumber\" : \"\", " + 
                    " \"email\" : \"1y8d\", " + 
                    " \"billingCountry\" : \"aPA6SVkpEtj7n_2s\", " + 
                    " \"pageSize\" : 257 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_putOnCheckoutsStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"\", " + 
                    " \"checkoutStatus\" : \"12hN1sur8akn0\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/orders/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_putOnOrdersStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"orderId\" : 67 " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/checkout/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_21_getOnOrdersCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/checkout/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/checkout/CLz31iBp8mbqRkl")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/checkout/CLz31iBp8mbqRkl"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_22_putOnPayment_methodShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzE4ODEsImlhdCI6MTc3NTUzMTU4MSwianRpIjoiYWRhMTg5NjUtMzMyMy00Y2MyLWFiOGYtOGJiZmY0MGNjYTQ1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4YWY4ZjIxLTkxMTgtNGU0ZS04MGQxLTBlNWUxN2RmMjI0NCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CmC-8nrrxHRPZn1u0P33XZBCWhmYpShUmJdjPE_qB2jTpJO25QBnUOlmYwR_eseMbFYAdTh118PGAzL7InH6Nes_z-sdgQwbeaDf85cllxTY0QMi-z35LEgouMocKJEVhLHi_-yxGiuooOqHimfAWvq0hbmwGRnTvTrEUs-GwGSI19i_DaZeDWDoXC1j4VQjLx8L7FcHH3XLTo0CFDH0GDcBst3nLh65QlL32fAxMEFQXzCV0C0w3icflZTu-0nTNAKbcdLOAxd3fBuD1q6ZiivhP6haE9WXZq8Fn0HAfy40ZvJgGuzzLfgJwfCtwUXboi25WEb4QDbEcy2Jh73X3g") // Fixed Headers
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/li1x90WOE_7wU/payment-method")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/li1x90WOE_7wU/payment-method"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/latest/{count}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/428")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_putOnPayment_methodReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"paymentMethodId\" : \"\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/UnVEEmN5bQHzPl/payment-method")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/UnVEEmN5bQHzPl/payment-method"));
    }


}
