/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T05:03:46.079580100Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 8
 * <br>
*  Used time: 0h 1m 4s
 * <br>
*  Needed budget for current results: 3%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_sampledata_admin_only_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5UnVxX2x3MGdHbXppekN6M183cmNYZXVWS24zaHpvQ21pVV9lT1B0Wm9vIn0.eyJleHAiOjE3Nzc1MjAzNDksImlhdCI6MTc3NzUxNjc0OSwianRpIjoiNDU1MzkwYjUtYTljZi00MDQzLThiODctZmUyZjE4MWYxNWZlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiJmMjNmMjQ4Ni1lOWVmLTQ3NGMtYjdlZS1hYjkwNzNlNDliOTkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImYzY2I0MmM4LTQzNGUtNDQ2MC1hZDQyLWZjZDI5ZDViZjJhNSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.hURWrHrD7yrmVBjNManxk70QLYZMSiGrlwa4ygjROvsvwPdjhamyKyyNue2iV_RcmMbXqeBUZhjhbNLbt0MYGkdRFGVr_tJo7T_2fYypf1zL-v1AAv0Iyr4Nad9p8Lc-q9xAMh3-dpx9eZkYMmVtn-m7jz5Y5slwkrdbNlV-RbK8zmTzxuSNO91pAHDG9h9uaaOU_1J4uSrqJT8Jhp33e4sZFf7uAL3jkXa2ltKwA6z2fzMwt5zZVBYWluDhogno2RcaFovPr2oJQvLJA3-6nK0uJXzehPvCkLDYI4hGkcN39dvr5yHal8mfXXZBvLfyRA7umo40GUJIfQVX-Yhe7g") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"message\" : \"kvMG91nqtm42\" " + 
                    " } ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"message\" : \"dhBsu_1HiIlIS\" " + 
                    " } ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }


}
