/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T20:59:21.851931191Z[GMT]
 * <br>
*  The generated test suite contains 26 tests
 * <br>
*  Covered targets: 91
 * <br>
*  Used time: 0h 1m 41s
 * <br>
*  Needed budget for current results: 63%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_customer_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) POST:/customer/storefront/user-address
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnUser_addressShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"stateOrProvinceId\" : 818, " + 
                    " \"countryId\" : 645 " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("403 Forbidden: [no body]"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers?pageNo=0")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing GET on path '/backoffice/customers' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers?pageNo=889")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnBackofficeCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing GET on path '/backoffice/customers' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"username\" : \"xZaOgqNI\", " + 
                    " \"email\" : \"woxy25mwK9Txd3L\", " + 
                    " \"firstName\" : \"lg\", " + 
                    " \"lastName\" : \"6qRL2ZEmxZffNTd\", " + 
                    " \"password\" : \"QYpg65m0sgc\", " + 
                    " \"role\" : \"OJla7SoOF6DcX\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"username\" : \"_veaqh7388ha31_\", " + 
                    " \"email\" : \"cxq4Yix1Hbq\", " + 
                    " \"firstName\" : \"mX0ALzqkpQs\", " + 
                    " \"lastName\" : \"Fm1eisruZh7i8Z\", " + 
                    " \"password\" : \"G\", " + 
                    " \"role\" : \"YVTgLeDqpX\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_postOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"contactName\" : \"eSak9zhht0F\", " + 
                    " \"phone\" : \"wVXC3nFCKexWknw7\", " + 
                    " \"addressLine1\" : \"fb1kYpyELLlWJP7r\", " + 
                    " \"zipCode\" : \"6t_N1\", " + 
                    " \"districtId\" : 189, " + 
                    " \"stateOrProvinceId\" : 193 " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address"));
    }
    
    
    /**
    * Calls:
    * (200) POST:/customer/storefront/customer/guest-user
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_postOnGuest_userReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 200 not defined for path '/storefront/customer/guest-user'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .post(baseUrlOfSut + "/customer/storefront/customer/guest-user")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'userId'", containsString("d44f4854-87fd-4e6d-9461-084bc44a24b0"))
                .body("'email'", containsString("LUj6_lkyha56ay3B_guest@yas.com"))
                .body("'password'", containsString("GUEST"));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_putOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing PUT on path '/storefront/user-address/{id}' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .put(baseUrlOfSut + "/customer/storefront/user-address/752")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/storefront/user-address/752")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/{email}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnCustomReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/{email}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/Kw2Z")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/storefront/customer/profile
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnProfileReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/storefront/customer/profile'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/customer/profile")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/backoffice/customers/{email}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnCustomReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing GET on path '/backoffice/customers/{email}' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers/FY_Zc9W10G2HA")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address/default-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnDefault_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/customer/storefront/user-address/default-address
    * 2 - (404) GET:/customer/storefront/user-address/default-address
    * Found 3 potential faults. Type-codes: 101, 204
    */
    @Test @Timeout(60)
    public void test_14_getOnDefault_addressShowsFaults_101_204() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/default-address'.
        // Fault204. Leakage Information Existence of Protected Resource.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/customer/guest-user
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_postOnGuest_userReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/customer/guest-user'.
        given().accept("*/*")
                .post(baseUrlOfSut + "/customer/storefront/customer/guest-user")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/customer/guest-user"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_putOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .put(baseUrlOfSut + "/customer/storefront/user-address/422")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/422"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_deleteOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/storefront/user-address/814")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/814"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/customer/storefront/user-address/default-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_getOnDefault_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_deleteOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/storefront/user-address/518")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_getOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/0JqU_S")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_getOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing GET on path '/backoffice/customers/profile/{id}' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/BN9")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"firstName\" : \"QXXv\", " + 
                    " \"email\" : \"ZjUrn\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/backoffice/customers/profile/FMFSZZSpZN")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_putOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"firstName\" : \"P0S\", " + 
                    " \"email\" : \"Aq8P2\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/backoffice/customers/profile/qDMDh_bcHOfl2")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/qDMDh_bcHOfl2"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_deleteOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkzNTgsImlhdCI6MTc3NTUwOTA1OCwianRpIjoiZjQ1YWY0NDQtZjU1Zi00ZDc4LWJmYWEtNmFmODIwZDZkYjkxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjU0MGU4MWQxLWMwNjYtNGNiMy04ZWEyLTlhODhhZjA5Y2E1MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.PSKXGq4asyA_Z6y-OVhp8vw0ec6_vsdv7vRe8bUc0EFUsGuEKHflqa2XxzCUxfKJ4xp4XcvcSker_dH_6_EvXG_yilpC0m-JCnpApz9AMXZA4Yag-0SKkLdph4GcmPLoXVwGbnL2WFgikjqJHLorO3JG_heO8yaLnj3NI2CfqfzAGturrPUeTkFOOxSkAAHe7HxBrjph-xyskDOUoQUIYAJhk54ZibFPIukwTBcy24Ep3LKhGIWnbRKo9j0_Nabfjyt9-ExICldXkwVVju54XZwYpYNpllphb1S9LhjpymVt-oY2YliGwENrL5_Ui3Sj-YJpTCtphnRG5SjJ2AUMlQ") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/backoffice/customers/profile/SzWc4XwxvH7ZwB23")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_deleteOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/backoffice/customers/profile/KaVJVcDzxKzteSz")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/KaVJVcDzxKzteSz"));
    }


}
