/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T04:30:26.390289214Z[GMT]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 26
 * <br>
*  Used time: 0h 1m 39s
 * <br>
*  Needed budget for current results: 81%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_rating_user_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_0_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzY0MjMsImlhdCI6MTc3NTUzNjEyMywianRpIjoiYzlhM2M2MTEtODZlOS00YmJhLThjMTgtMTJlMGQ2NGY4MzhlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImIzNWFkY2IxLWU4YWYtNDBlNS05MjdmLWM2YWVkMTAwZWYyMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.ZHsz3Ge2LfCv7STnCAgPtll2KhUHEiQQ-Psw0KbJwwJU5gHH24QAZgWTR0mjyg7BXvEI2EagS7O0SSejJwIFEdFg9W7yhv9uqWPWxgo_QJ62S2DLTzwwJZeUCyFnbLHi_C4iCO9ByvokrKe9SkC3qa-SCKuTezffAaKroa1bBaOHR92Tf-kbvJeWpbaHsrDWZ8LSE7WpQGQQ7MfVKJiArBeSq8CM09HkcqNSqtYEUERQSkdsQDLOtWw6GBuSf_rSSEoj0Ll7vp9WIwfsveuQ0reSVpLI_N2ePz7KYSC-Bwr7WNZrZQ15eertPemRm7haN31Fxm0f72fCsRgqTwOKMA") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/854?pageNo=984")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_1_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzY0MjMsImlhdCI6MTc3NTUzNjEyMywianRpIjoiYzlhM2M2MTEtODZlOS00YmJhLThjMTgtMTJlMGQ2NGY4MzhlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImIzNWFkY2IxLWU4YWYtNDBlNS05MjdmLWM2YWVkMTAwZWYyMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.ZHsz3Ge2LfCv7STnCAgPtll2KhUHEiQQ-Psw0KbJwwJU5gHH24QAZgWTR0mjyg7BXvEI2EagS7O0SSejJwIFEdFg9W7yhv9uqWPWxgo_QJ62S2DLTzwwJZeUCyFnbLHi_C4iCO9ByvokrKe9SkC3qa-SCKuTezffAaKroa1bBaOHR92Tf-kbvJeWpbaHsrDWZ8LSE7WpQGQQ7MfVKJiArBeSq8CM09HkcqNSqtYEUERQSkdsQDLOtWw6GBuSf_rSSEoj0Ll7vp9WIwfsveuQ0reSVpLI_N2ePz7KYSC-Bwr7WNZrZQ15eertPemRm7haN31Fxm0f72fCsRgqTwOKMA") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/739?pageSize=651")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_2_getOnRatingsProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/984")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_3_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzY0MjMsImlhdCI6MTc3NTUzNjEyMywianRpIjoiYzlhM2M2MTEtODZlOS00YmJhLThjMTgtMTJlMGQ2NGY4MzhlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImIzNWFkY2IxLWU4YWYtNDBlNS05MjdmLWM2YWVkMTAwZWYyMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.ZHsz3Ge2LfCv7STnCAgPtll2KhUHEiQQ-Psw0KbJwwJU5gHH24QAZgWTR0mjyg7BXvEI2EagS7O0SSejJwIFEdFg9W7yhv9uqWPWxgo_QJ62S2DLTzwwJZeUCyFnbLHi_C4iCO9ByvokrKe9SkC3qa-SCKuTezffAaKroa1bBaOHR92Tf-kbvJeWpbaHsrDWZ8LSE7WpQGQQ7MfVKJiArBeSq8CM09HkcqNSqtYEUERQSkdsQDLOtWw6GBuSf_rSSEoj0Ll7vp9WIwfsveuQ0reSVpLI_N2ePz7KYSC-Bwr7WNZrZQ15eertPemRm7haN31Fxm0f72fCsRgqTwOKMA") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/4324903262966495063/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_4_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/723/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }


}
