/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T20:57:37.626524225Z[GMT]
 * <br>
*  The generated test suite contains 6 tests
 * <br>
*  Covered targets: 23
 * <br>
*  Used time: 0h 1m 36s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_media_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (403) POST:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkyNTgsImlhdCI6MTc3NTUwODk1OCwianRpIjoiOGEyYWRjYmUtYmZmNy00NzVmLWFmNzUtMmQ3N2E0Mzk3NmU3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0NzA4ZTdkLTI3YTctNDQ0Ny04ZmY2LWI3MTI0Yjk2MmJhZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qb4IvVeAd7fNfD-5QplWQSfsArsN4809TuPEE6m2pMbsZ3iho6hNS55krQiNMRn4PRAAKmihwrygVKGjZrRYIBlmj8IrD939ypZqr6wtyzESOU3lEdwhuO3_lPMycbZM0cP-8_EFEcwXtYQ6QG09nOIQPukL8Vfi4U212AM4z1uN9rfK_lGvg2KdMnmsudDeGCHYNWVQFtMOozkKLlvzLIYn_XuoffI9N0RYeyQNoX8b_eA7jfmjEwo3zccldfoyZ4IjB0613t6hBWDuXCYmLKhiEwQzOV6aFFOGctiXB9EkUvjbwmUiJ7VL8PA1onpBTtZxlZPgh3sW-p6nNT_SUA") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/medias'.
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("multipartFile=u")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkyNTgsImlhdCI6MTc3NTUwODk1OCwianRpIjoiOGEyYWRjYmUtYmZmNy00NzVmLWFmNzUtMmQ3N2E0Mzk3NmU3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0NzA4ZTdkLTI3YTctNDQ0Ny04ZmY2LWI3MTI0Yjk2MmJhZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qb4IvVeAd7fNfD-5QplWQSfsArsN4809TuPEE6m2pMbsZ3iho6hNS55krQiNMRn4PRAAKmihwrygVKGjZrRYIBlmj8IrD939ypZqr6wtyzESOU3lEdwhuO3_lPMycbZM0cP-8_EFEcwXtYQ6QG09nOIQPukL8Vfi4U212AM4z1uN9rfK_lGvg2KdMnmsudDeGCHYNWVQFtMOozkKLlvzLIYn_XuoffI9N0RYeyQNoX8b_eA7jfmjEwo3zccldfoyZ4IjB0613t6hBWDuXCYmLKhiEwQzOV6aFFOGctiXB9EkUvjbwmUiJ7VL8PA1onpBTtZxlZPgh3sW-p6nNT_SUA") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias?ids=637&ids=-9036992838287653013&ids=-3723064578632724328&ids=472")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/media/medias/657")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias/657"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkyNTgsImlhdCI6MTc3NTUwODk1OCwianRpIjoiOGEyYWRjYmUtYmZmNy00NzVmLWFmNzUtMmQ3N2E0Mzk3NmU3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0NzA4ZTdkLTI3YTctNDQ0Ny04ZmY2LWI3MTI0Yjk2MmJhZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qb4IvVeAd7fNfD-5QplWQSfsArsN4809TuPEE6m2pMbsZ3iho6hNS55krQiNMRn4PRAAKmihwrygVKGjZrRYIBlmj8IrD939ypZqr6wtyzESOU3lEdwhuO3_lPMycbZM0cP-8_EFEcwXtYQ6QG09nOIQPukL8Vfi4U212AM4z1uN9rfK_lGvg2KdMnmsudDeGCHYNWVQFtMOozkKLlvzLIYn_XuoffI9N0RYeyQNoX8b_eA7jfmjEwo3zccldfoyZ4IjB0613t6hBWDuXCYmLKhiEwQzOV6aFFOGctiXB9EkUvjbwmUiJ7VL8PA1onpBTtZxlZPgh3sW-p6nNT_SUA") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias/688")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MDkyNTgsImlhdCI6MTc3NTUwODk1OCwianRpIjoiOGEyYWRjYmUtYmZmNy00NzVmLWFmNzUtMmQ3N2E0Mzk3NmU3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0NzA4ZTdkLTI3YTctNDQ0Ny04ZmY2LWI3MTI0Yjk2MmJhZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qb4IvVeAd7fNfD-5QplWQSfsArsN4809TuPEE6m2pMbsZ3iho6hNS55krQiNMRn4PRAAKmihwrygVKGjZrRYIBlmj8IrD939ypZqr6wtyzESOU3lEdwhuO3_lPMycbZM0cP-8_EFEcwXtYQ6QG09nOIQPukL8Vfi4U212AM4z1uN9rfK_lGvg2KdMnmsudDeGCHYNWVQFtMOozkKLlvzLIYn_XuoffI9N0RYeyQNoX8b_eA7jfmjEwo3zccldfoyZ4IjB0613t6hBWDuXCYmLKhiEwQzOV6aFFOGctiXB9EkUvjbwmUiJ7VL8PA1onpBTtZxlZPgh3sW-p6nNT_SUA") // Fixed Headers
                .delete(baseUrlOfSut + "/media/medias/6131290312180335907")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Media 6131290312180335907 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
