/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T02:35:40.300064268Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 8
 * <br>
*  Used time: 0h 1m 3s
 * <br>
*  Needed budget for current results: 3%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_sampledata_user_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLcTh2dHJEazBLOGpLX1c5NWJreTFKaTN5RzRSMy1oUmc1dzY3NDVkZ3RRIn0.eyJleHAiOjE3Nzg0MTcwNjYsImlhdCI6MTc3ODQxNjc2NiwianRpIjoiMWI0M2U2Y2ItMWI0Yi00NThhLTg1N2EtNzViNzZmMWI3ZDU3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzNjVlNmUwOC01Y2YyLTQ0YzktODg0NC00M2M3OGRkYjk4MWYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI1OGE2OTUzLWJiNGMtNGI0ZC05MDk5LWNiYjA2MThlY2ZjZiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.r7H-7cKAVpODNqoRzvNvUtH6_XuabK5hcp__1hg5TuLjGwBsLmhXnWGfp7FGJBCCzwGV_9y_dqJ0bUJhT4WBGoYrzi5vTmktBAXzVuOBkKKsBPiy96ihP7duQC3tyoNpj0Pj8LQW8KRQHRji1GkajDfcCRQuIePt0diZXI2SazFRRHPlrnS7P0khODa0uzLB8y0gtqhLFcOiHHmwTcr7MwhcXgqyE01SsDnELYPNT_LNhTSa4LJ-5Ia_CAtRogPQkXE8dIJs1Gi9KuJWXcRJlbJQXkKrO4ncbD-d8R--XttJcZhJsz0678n_kBdj_NmThlennDJFfB5Gg3zaxLo08w") // Fixed Headers
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }


}
