/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T03:40:23.425035978Z[GMT]
 * <br>
*  The generated test suite contains 27 tests
 * <br>
*  Covered targets: 112
 * <br>
*  Used time: 0h 1m 31s
 * <br>
*  Needed budget for current results: 68%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_tax_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"ytsD8rdGkHP\", " + 
                    " \"name\" : \"l4e9sGNfJRq0_gn\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : -6.720272688785394E8, " + 
                    " \"taxClassId\" : 588, " + 
                    " \"stateOrProvinceId\" : 304, " + 
                    " \"countryId\" : 97 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"Ap5vg4\", " + 
                    " \"name\" : \"_MNOtk\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 8.298104378966251E7, " + 
                    " \"zipCode\" : \"Noc1CIa4st\", " + 
                    " \"taxClassId\" : 963, " + 
                    " \"countryId\" : 950 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnLocation_based_batchReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=270002505819253687&taxClassIds=8132931831812844817&" + 
                    "countryId=971")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageNo=768")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_getOnTax_ratesTax_percentWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=8959250547599544139&" + 
                    "countryId=614&" + 
                    "zipCode=2Og9YBf6Sc")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/917")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/907")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnLocation_based_batchReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=779&taxClassIds=740&taxClassIds=150&taxClassIds=963&taxClassIds=305&" + 
                    "countryId=542&" + 
                    "zipCode=vKkJEICDWs9Lq")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageNo=919")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnTax_ratesTax_percentWithQueryParamsNegativeStateOrProvinceIdReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=6979811210730170646&" + 
                    "countryId=914&" + 
                    "stateOrProvinceId=-2821509768923920938")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/-834162641")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/190791849")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"231\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/231")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 669.0, " + 
                    " \"taxClassId\" : 39, " + 
                    " \"countryId\" : 836 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/669")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"995\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/995")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/995"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 622.0, " + 
                    " \"zipCode\" : \"wisj\", " + 
                    " \"taxClassId\" : 41, " + 
                    " \"countryId\" : 2735149537455970093 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/622")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/622"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : -7.047342199021437E18, " + 
                    " \"taxClassId\" : 624, " + 
                    " \"countryId\" : 158 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/-7047342199021437065")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/-1529917342")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzM0MjgsImlhdCI6MTc3NTUzMzEyOCwianRpIjoiNTY0NjZkMWEtYzA2ZS00MmY5LTljZDEtMGQ3ODU3M2Q3YWU4IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiOGRiYzMzLWIxNWEtNDg1ZC04MjcwLTAyNDI4YjZkOWQwZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.SvG4vwbFvYXcnIGJbqy-NNlX_e3Z4TuE4cC7MIl9etg8LzTU6HiEH_6mXHUntqQz_3pg7LOvcRGdDzoYvJn4UZJi3O4atbXuF4dVvfz9irQeFCzUdKgcP4EzscM17C_jOQ-zheX-i74VIQKQ1C2IQAHpBjhxOoyrKXSmjfRlOlp7yO7R-ZvGUG7WTfU_sNbpygMCWBgS3yM1QELBrszFFUtIpMhSq5UIDmcIRQ1jpMH4wwvSjrOCshwqICuiE7rYscpNNP7v_GWDat5p48oM5ZHlWGZUw97vyo6VqeCsF9bIVVuqHjDyT39yQcZTUducZyJPQmMr-35U0mKWvTjrQw") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/445")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/524")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/524"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_26_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/657")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/657"));
    }


}
