/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T01:36:52.877074823Z[GMT]
 * <br>
*  The generated test suite contains 26 tests
 * <br>
*  Covered targets: 113
 * <br>
*  Used time: 0h 1m 30s
 * <br>
*  Needed budget for current results: 34%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_tax_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"JoeMc3o2Li79u\", " + 
                    " \"name\": \"16fvh_DvC_V\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\": 0.19037392238002948, " + 
                    " \"zipCode\": \"HPJOH7ZRQC\", " + 
                    " \"taxClassId\": 535, " + 
                    " \"stateOrProvinceId\": 726, " + 
                    " \"countryId\": 908 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"2xJIqAlH\", " + 
                    " \"name\": \"GB_j11zr\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\": 0.3383599913789712, " + 
                    " \"zipCode\": \"G\", " + 
                    " \"taxClassId\": 94, " + 
                    " \"countryId\": 95 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnTax_classesPagingWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging?" + 
                    "pageNo=424&" + 
                    "pageSize=354")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnTax_ratesLocation_based_batchWithQueryParamsNegativeCountryId() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=576&taxClassIds=2387262921513771697&taxClassIds=986&" + 
                    "countryId=-627637659299478970&" + 
                    "stateOrProvinceId=520&" + 
                    "zipCode=Io5xkTaikrTFQ")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageSize=982")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_getOnTax_percentReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=79&" + 
                    "countryId=842")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/-5317983862186368976")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 401 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/37")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnTax_classesPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnTax_ratesLocation_based_batchWithQueryParams() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=547&taxClassIds=130&" + 
                    "countryId=992")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageSize=802")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnTax_percentReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=877&" + 
                    "countryId=1197365893")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/-6095684871188208977")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/992")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"540\", " + 
                    " \"name\": \"t4QtKIG_\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/540")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\": 466.0, " + 
                    " \"zipCode\": \"\", " + 
                    " \"taxClassId\": 2393420126382814429, " + 
                    " \"stateOrProvinceId\": 32, " + 
                    " \"countryId\": -4095029859644073674 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/466")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": \"558\", " + 
                    " \"name\": \"UnNSQhRif8kL\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/558")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/558"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\": 172.0, " + 
                    " \"zipCode\": \"XsZz6EMu\", " + 
                    " \"taxClassId\": -322137046942776209, " + 
                    " \"countryId\": 150484156 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/172")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/172"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/721")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjYwMTksImlhdCI6MTc3NTUyNTcxOSwianRpIjoiM2YyOWU0MmEtNjExMS00OTUxLTlhNDEtYmZhNmQ5ODIzZGMxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZmYzI1N2ViLWMwZDItNGIyYy04MTA1LWRhMmZmYjgwNzIwYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.diRKB7cMJVGzLtswCTAk5e0MGiZZiz6oqeg5cYRlJuYh4qevSP4JSL7AXFYx_10X06BrEircaiUYTrir8f4Spvr3Twku6rTp4i42TwEkGAoUhYY_ap6KykkdKBRl60KmsKd-ZRumKWLYuMkpE5YlRJcQtW79c49jhgH9kdHQUT8GcMDroIbKlBtPACU6n1V6d4FX7zSY-_2hRXOEKV9z7vbG5HT_I3iUqTVqC1bM1aUzx2tN5qtMkzUZe7i43-7AUMOZLSn9codeqe0Vwo7kjx9SnudvSr-Y6a5gdN4jZ1LIfWVf44u7kagmgj3IMFi0TDn-sToh3OQeM03WfUTIZg") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/832")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/722")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/722"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/782")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/782"));
    }


}
