/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T03:42:35.412469274Z[GMT]
 * <br>
*  The generated test suite contains 23 tests
 * <br>
*  Covered targets: 74
 * <br>
*  Used time: 0h 2m 0s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
*/
public class EvoMaster_product_admin_only_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute-groups
    */
    @Test @Timeout(60)
    public void test_0_postOnProduct_attribute_groupsReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"1fq4JZ\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute-groups")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name 1fq4JZ is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute-value
    */
    @Test @Timeout(60)
    public void test_1_postOnProduct_attribute_valueReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\": 112, " + 
                    " \"productAttributeId\": 611, " + 
                    " \"value\": \"1dNOstnBWHv_GG\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute-value")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Product 112 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute
    */
    @Test @Timeout(60)
    public void test_2_postOnProduct_attributeReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"5EsFy1_VZbi\", " + 
                    " \"productAttributeGroupId\": 719 " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Product attribute group 719 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-options
    */
    @Test @Timeout(60)
    public void test_3_postOnProduct_optionsReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"9oZ\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-options")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name 9oZ is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-template
    */
    @Test @Timeout(60)
    public void test_4_postOnProduct_templateReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"WNy_iuAtC5W\", " + 
                    " \"productAttributeTemplates\": [] " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-template")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name WNy_iuAtC5W is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) GET:/product/backoffice/product-attribute-value/{productId}
    */
    @Test @Timeout(60)
    public void test_5_getOnProduct_attribute_valuReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/product-attribute-value/480")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Product 480 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/product-variations/{id}
    */
    @Test @Timeout(60)
    public void test_6_getOnBackofficeProduct_variReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/product-variations/745")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 745 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-variations/{id}
    */
    @Test @Timeout(60)
    public void test_7_getOnStorefrontProduct_variReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-variations/-1740224778760476708")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product -1740224778760476708 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/products/{productId}
    */
    @Test @Timeout(60)
    public void test_8_getOnBackofficeProductReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/products/755")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 755 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-values/{productId}
    */
    @Test @Timeout(60)
    public void test_9_getOnProduct_option_valuReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-values/513")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 513 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product/{slug}
    */
    @Test @Timeout(60)
    public void test_10_getOnStorefrontProductReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product/DsPkhRfSuReG4R")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product DsPkhRfSuReG4R is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/products-es/{productId}
    */
    @Test @Timeout(60)
    public void test_11_getOnProducts_Returns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/products-es/199")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 199 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/product/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_12_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/product/v3/api-docs")
                .then()
                .statusCode(404);
    }
    
    
    /**
    * Calls:
    * (404) PUT:/product/backoffice/brands/{id}
    */
    @Test @Timeout(60)
    public void test_13_putOnBrandReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"QIACecDaCcYgIU\", " + 
                    " \"slug\": \"hX7jXCHEZ\", " + 
                    " \"isPublish\": true " + 
                    " } ")
                .put(baseUrlOfSut + "/product/backoffice/brands/546")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Brand 546 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/product/backoffice/brands/{id}
    */
    @Test @Timeout(60)
    public void test_14_deleteOnBrandReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .delete(baseUrlOfSut + "/product/backoffice/brands/-1586195691011979335")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Brand -1586195691011979335 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/category/{categorySlug}/products
    */
    @Test @Timeout(60)
    public void test_15_getOnCategoriProductsWithQueryParamsReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/category/6vU/products?" + 
                    "pageNo=428&" + 
                    "pageSize=786")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Category 6vU is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/category/{categorySlug}/products
    */
    @Test @Timeout(60)
    public void test_16_getOnCategoriProductsWithQueryParamReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/category/XzCwpq2ILuJV7d1N/products?pageNo=1936530045")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Category XzCwpq2ILuJV7d1N is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/products/related-products/{id}
    */
    @Test @Timeout(60)
    public void test_17_getOnRelated_productReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/products/related-products/257")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 257 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/brand/{brandSlug}/products
    */
    @Test @Timeout(60)
    public void test_18_getOnBrandProductsReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/brand/cP/products")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Brand cP is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-combinations/{productId}/values
    */
    @Test @Timeout(60)
    public void test_19_getOnValuesReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-combinations/530/values")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 530 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/productions/{id}/slug
    */
    @Test @Timeout(60)
    public void test_20_getOnSlugReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/productions/277/slug")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 277 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/products/detail/{productId}
    */
    @Test @Timeout(60)
    public void test_21_getOnDetailReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/products/detail/913")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 913 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/products/related-products/{id}
    */
    @Test @Timeout(60)
    public void test_22_getOnRelated_productReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTAzMjksImlhdCI6MTc3NDQxMDAyOSwianRpIjoiYmFjYTY4ZTktYWJkMy00NWNiLWFlN2EtOGRkZDk0ZjEwZTM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjI0MWI0OTkxLTY5NDYtNGU3ZS05MjY1LTZkNTZlNDM0ZGM2OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.SSBA2DSJedBah1uSbpsiudhtusNDlRguZlknQxuin-jrNVX-e6Mmc13ZnG_5Mmnu2kRj-xXa0gLduc3S37c2EqFgUau6TnUGXnwj7x5g3t3cwHMj7NxVIrnK-fG_EiyzD1vhauBV-GYkG1i4TcqHoCf7TUSiC9nyyjTm9VVg39i2w34eTvjowhTsDuUQa357ljwYzUMD3_Ayw_dK1fOuaKLj9snK-58ALt1dSazHJxKj8Nx6Sc5EjHrAXz4M7xI6r_RQHogYFV3I7hrIYlmcbX2DD65ibIYCriCBEFouTofZnwNKi74W6siXBU7_Lzv9WWiTpHZgxP6-DYEiungOyw") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/products/related-products/531")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 531 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
