/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-06T21:49:10.529875399Z[GMT]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 72
 * <br>
*  Used time: 0h 1m 55s
 * <br>
*  Needed budget for current results: 68%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_promotion_super_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_0_getOnPromotionsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTIzMzIsImlhdCI6MTc3NTUxMjAzMiwianRpIjoiODVjNjdkY2MtYjViMy00ODI1LWFmM2ItYmY3YzNkMGQ1MjkwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjhmOGExNjY5LTU0ODgtNGE0MS1hNzM4LTk4MTE0MDIyYWM2ZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.qPcsVchbE4EKwzfyGxKmbZ0gygkzqhWBisIPoZ8lv1-GeNSmR1-IU8g4JEVtTohHCGPnbpjqo5uHxh1gIyhUnAm1Iqq18l6YHk-tln0P4fCoFXEPYq97rI9QIw7RC9KEbtxfdbsi45OpfGPkaBkN-007ZxyStqUwM4xXBlHu7OWOSar_7GKmwSWa5QeA5RKXyXfiAi9g94FKBf9Wd8NxWEIQXUEROQYMTSfeg6p5Sy5guEABPLkIYvsZHykPqEx1X8XZU6S7VBLOD00VNcnE3xz4Y6KApgLGEtfoI9RKNCWNZBBixql_SuACWJRa38yRswg9XFp3ToYyN_FoZXIGKw") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "startDate=1982-04-25T10%3A19%3A29Z&" + 
                    "endDate=2050-12-15T02%3A55%3A39Z")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(5))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_1_getOnPromotionsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTIzMzIsImlhdCI6MTc3NTUxMjAzMiwianRpIjoiODVjNjdkY2MtYjViMy00ODI1LWFmM2ItYmY3YzNkMGQ1MjkwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjhmOGExNjY5LTU0ODgtNGE0MS1hNzM4LTk4MTE0MDIyYWM2ZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.qPcsVchbE4EKwzfyGxKmbZ0gygkzqhWBisIPoZ8lv1-GeNSmR1-IU8g4JEVtTohHCGPnbpjqo5uHxh1gIyhUnAm1Iqq18l6YHk-tln0P4fCoFXEPYq97rI9QIw7RC9KEbtxfdbsi45OpfGPkaBkN-007ZxyStqUwM4xXBlHu7OWOSar_7GKmwSWa5QeA5RKXyXfiAi9g94FKBf9Wd8NxWEIQXUEROQYMTSfeg6p5Sy5guEABPLkIYvsZHykPqEx1X8XZU6S7VBLOD00VNcnE3xz4Y6KApgLGEtfoI9RKNCWNZBBixql_SuACWJRa38yRswg9XFp3ToYyN_FoZXIGKw") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "pageNo=951&" + 
                    "promotionName=&" + 
                    "startDate=2042-10-25T07%3A52%3A41.070-09%3A26")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(951))
                .body("'pageSize'", numberMatches(5))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_2_getOnPromotionsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTIzMzIsImlhdCI6MTc3NTUxMjAzMiwianRpIjoiODVjNjdkY2MtYjViMy00ODI1LWFmM2ItYmY3YzNkMGQ1MjkwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjhmOGExNjY5LTU0ODgtNGE0MS1hNzM4LTk4MTE0MDIyYWM2ZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.qPcsVchbE4EKwzfyGxKmbZ0gygkzqhWBisIPoZ8lv1-GeNSmR1-IU8g4JEVtTohHCGPnbpjqo5uHxh1gIyhUnAm1Iqq18l6YHk-tln0P4fCoFXEPYq97rI9QIw7RC9KEbtxfdbsi45OpfGPkaBkN-007ZxyStqUwM4xXBlHu7OWOSar_7GKmwSWa5QeA5RKXyXfiAi9g94FKBf9Wd8NxWEIQXUEROQYMTSfeg6p5Sy5guEABPLkIYvsZHykPqEx1X8XZU6S7VBLOD00VNcnE3xz4Y6KApgLGEtfoI9RKNCWNZBBixql_SuACWJRa38yRswg9XFp3ToYyN_FoZXIGKw") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "pageSize=425&" + 
                    "couponCode=UgdJyXDBQOuWR")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(425))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) POST:/promotion/storefront/promotions/updateUsage
    */
    @Test @Timeout(60)
    public void test_3_postOnUpdateUsageReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MTIzMzIsImlhdCI6MTc3NTUxMjAzMiwianRpIjoiODVjNjdkY2MtYjViMy00ODI1LWFmM2ItYmY3YzNkMGQ1MjkwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjhmOGExNjY5LTU0ODgtNGE0MS1hNzM4LTk4MTE0MDIyYWM2ZCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.qPcsVchbE4EKwzfyGxKmbZ0gygkzqhWBisIPoZ8lv1-GeNSmR1-IU8g4JEVtTohHCGPnbpjqo5uHxh1gIyhUnAm1Iqq18l6YHk-tln0P4fCoFXEPYq97rI9QIw7RC9KEbtxfdbsi45OpfGPkaBkN-007ZxyStqUwM4xXBlHu7OWOSar_7GKmwSWa5QeA5RKXyXfiAi9g94FKBf9Wd8NxWEIQXUEROQYMTSfeg6p5Sy5guEABPLkIYvsZHykPqEx1X8XZU6S7VBLOD00VNcnE3xz4Y6KApgLGEtfoI9RKNCWNZBBixql_SuACWJRa38yRswg9XFp3ToYyN_FoZXIGKw") // Fixed Headers
                .contentType("application/json")
                .body(" [ ] ")
                .post(baseUrlOfSut + "/promotion/storefront/promotions/updateUsage")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
