/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T04:20:01.960121669Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 22
 * <br>
*  Used time: 0h 2m 7s
 * <br>
*  Needed budget for current results: 96%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_promotion_super_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_0_getOnPromotionsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzU3NzEsImlhdCI6MTc3NTUzNTQ3MSwianRpIjoiOTViZjdlYTgtN2EzNy00YTk1LWIyZjUtNjc4MTE5Yjg1MmI5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE2MjdkMDZmLWYwZDYtNDQwOC1hZjRmLWI0ODA2MjAyZTgyNSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.q7sUeHh-sYQvpufLi8NC_2yz7a2MD4IWyPNqnBXIeMCczsbzKjihEHQkoDGBziXNM5FcIS272Qv0hJKsdHL71xIlkg8qwf12laGZxUVGxUshmpNLvQO1F1JL8IlWQHVJenJqVyltlTOmcI0dsGBtZvZEqAOM0Bp-pUc68ATDZ4VACs4W5fct8NOazRDwB6Bdbx0TBzs8b4z_h3-OuglusXCMzFdnlm_k1F6aQZsdBKf_4w8fNcafic232M2DYfZRKaZ4-Q1-TMoo1vNoYp3IR_3tdeyevH0Yk_0o8cDB4d2XzDLRLDc-OEkeVKfHvBBHyYVQb-TsDdeL9AAjz64R4Q") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "pageNo=0&" + 
                    "pageSize=978&" + 
                    "promotionName=N1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(978))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_1_getOnPromotionsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzU3NzEsImlhdCI6MTc3NTUzNTQ3MSwianRpIjoiOTViZjdlYTgtN2EzNy00YTk1LWIyZjUtNjc4MTE5Yjg1MmI5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE2MjdkMDZmLWYwZDYtNDQwOC1hZjRmLWI0ODA2MjAyZTgyNSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.q7sUeHh-sYQvpufLi8NC_2yz7a2MD4IWyPNqnBXIeMCczsbzKjihEHQkoDGBziXNM5FcIS272Qv0hJKsdHL71xIlkg8qwf12laGZxUVGxUshmpNLvQO1F1JL8IlWQHVJenJqVyltlTOmcI0dsGBtZvZEqAOM0Bp-pUc68ATDZ4VACs4W5fct8NOazRDwB6Bdbx0TBzs8b4z_h3-OuglusXCMzFdnlm_k1F6aQZsdBKf_4w8fNcafic232M2DYfZRKaZ4-Q1-TMoo1vNoYp3IR_3tdeyevH0Yk_0o8cDB4d2XzDLRLDc-OEkeVKfHvBBHyYVQb-TsDdeL9AAjz64R4Q") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "pageNo=0&" + 
                    "pageSize=990&" + 
                    "promotionName=LYiK")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(990))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }


}
