/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T04:10:12.154420060Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 19
 * <br>
*  Used time: 0h 1m 19s
 * <br>
*  Needed budget for current results: 90%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_rating_super_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_0_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/484?pageSize=33")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_1_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MzUyMjksImlhdCI6MTc3NTUzNDkyOSwianRpIjoiY2Y2MGJlNmUtYzdhMy00MjEwLWI1NTctMzM2ZjY0MTczMGYzIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2MjE0YzU4Mi05YTQ3LTQ3MDAtYWE5YS01Mjc1YjMzY2NiMGQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjJkODJhNWE0LWYxOTYtNDM5OC1hYjdhLWY2OGU1NDIwYWExNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJTVVBFUi1BRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXBlcl9hZG1pbiJ9.JbOLzwI65HjIr3WlBJDeYCt7jIl5m67IXNxno9CI5BhYghmuSbFFjaSueehoy4G6nQ-9Tj9DDH_N7gDOg4_IQjgMtlip_ntO0_o1kxn2FdvKynZuT4yHh4Eg6CMzwrZx4PL6ZofhJq0VCG7NCEwhsxcgT0XhkAGAyKPHWQ58tXNthi-BClNnfg3HMXPjTfjWnxqzUsxwUjntzR7xDlvwdvcYPKapTVMgxT_n6OJzT_7YErQZjDFmWjO62JtVRcgYQYFzogw8e2ipb6aWDws3qyaaG_VU0D6H1iUcGvD7_TzLijAjSX5-yOCIlfnZj2W4PD3DMf-lgFhHLl8Xs3xsXA") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/440/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_2_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/492/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }


}
