/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T02:20:26.937779351Z[GMT]
 * <br>
*  The generated test suite contains 6 tests
 * <br>
*  Covered targets: 23
 * <br>
*  Used time: 0h 1m 16s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_media_user_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (403) POST:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1Mjg2NDcsImlhdCI6MTc3NTUyODM0NywianRpIjoiYTIzNjdjNTgtZWUyZi00MzZhLTg4MWYtYmFlYzA5YTBmMTYwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjM5MGI1NzlhLTI1MjMtNDJlMC1hYTRjLTI1N2Y2MmY2NTUzMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.RJ9f1ZBo2rPXsq3Kd2fz-O4OonxL8_U9DeCHP7_9vEnYxm8Rd3u-bP41qxprrE8utQjr7VDTMUsAyVmBrVlGnRLtigxDmTpKFRSN_i6MiuRBtG9J-S4qttqCej7LIAfeVMAYq11A9wJIKHZFCIjyyBqloHITdWu07sfRgGclKzBW6jUrMxRnfuU2xfgKf-5BggdgmpZUnKQHYe5srxnLOIJQ81CXIVvMfMV_9WFQXYV7-wUvix_DgMwE2UQVNQ3k9a2ey_Pk2214C1VMd-xspLkv88WAO67XbB467L38RPzcASOO5JQFALhIr0938Tlb0r9mlVMmhU_ZFkBvfSyH7g") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/medias'.
        given().accept("*/*")
                .contentType("application/x-www-form-urlencoded")
                .body("multipartFile=F_41FyFHAan")
                .post(baseUrlOfSut + "/media/medias")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnMediasReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1Mjg2NDcsImlhdCI6MTc3NTUyODM0NywianRpIjoiYTIzNjdjNTgtZWUyZi00MzZhLTg4MWYtYmFlYzA5YTBmMTYwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjM5MGI1NzlhLTI1MjMtNDJlMC1hYTRjLTI1N2Y2MmY2NTUzMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.RJ9f1ZBo2rPXsq3Kd2fz-O4OonxL8_U9DeCHP7_9vEnYxm8Rd3u-bP41qxprrE8utQjr7VDTMUsAyVmBrVlGnRLtigxDmTpKFRSN_i6MiuRBtG9J-S4qttqCej7LIAfeVMAYq11A9wJIKHZFCIjyyBqloHITdWu07sfRgGclKzBW6jUrMxRnfuU2xfgKf-5BggdgmpZUnKQHYe5srxnLOIJQ81CXIVvMfMV_9WFQXYV7-wUvix_DgMwE2UQVNQ3k9a2ey_Pk2214C1VMd-xspLkv88WAO67XbB467L38RPzcASOO5JQFALhIr0938Tlb0r9mlVMmhU_ZFkBvfSyH7g") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias?ids=-1892926&ids=811&ids=-300374619")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 403 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/media/medias/234")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403.0))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/media/medias/234"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1Mjg2NDcsImlhdCI6MTc3NTUyODM0NywianRpIjoiYTIzNjdjNTgtZWUyZi00MzZhLTg4MWYtYmFlYzA5YTBmMTYwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjM5MGI1NzlhLTI1MjMtNDJlMC1hYTRjLTI1N2Y2MmY2NTUzMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.RJ9f1ZBo2rPXsq3Kd2fz-O4OonxL8_U9DeCHP7_9vEnYxm8Rd3u-bP41qxprrE8utQjr7VDTMUsAyVmBrVlGnRLtigxDmTpKFRSN_i6MiuRBtG9J-S4qttqCej7LIAfeVMAYq11A9wJIKHZFCIjyyBqloHITdWu07sfRgGclKzBW6jUrMxRnfuU2xfgKf-5BggdgmpZUnKQHYe5srxnLOIJQ81CXIVvMfMV_9WFQXYV7-wUvix_DgMwE2UQVNQ3k9a2ey_Pk2214C1VMd-xspLkv88WAO67XbB467L38RPzcASOO5JQFALhIr0938Tlb0r9mlVMmhU_ZFkBvfSyH7g") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias/889")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/media/medias/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_deleteOnMediaReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 404 not defined for path '/medias/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1Mjg2NDcsImlhdCI6MTc3NTUyODM0NywianRpIjoiYTIzNjdjNTgtZWUyZi00MzZhLTg4MWYtYmFlYzA5YTBmMTYwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI1ZmI4YTU4Mi05MjAwLTQ0NGUtOGU4YS1jNTY3NzY5NmVmMDYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjM5MGI1NzlhLTI1MjMtNDJlMC1hYTRjLTI1N2Y2MmY2NTUzMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJVU0VSIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzZXJfcm9sZSJ9.RJ9f1ZBo2rPXsq3Kd2fz-O4OonxL8_U9DeCHP7_9vEnYxm8Rd3u-bP41qxprrE8utQjr7VDTMUsAyVmBrVlGnRLtigxDmTpKFRSN_i6MiuRBtG9J-S4qttqCej7LIAfeVMAYq11A9wJIKHZFCIjyyBqloHITdWu07sfRgGclKzBW6jUrMxRnfuU2xfgKf-5BggdgmpZUnKQHYe5srxnLOIJQ81CXIVvMfMV_9WFQXYV7-wUvix_DgMwE2UQVNQ3k9a2ey_Pk2214C1VMd-xspLkv88WAO67XbB467L38RPzcASOO5JQFALhIr0938Tlb0r9mlVMmhU_ZFkBvfSyH7g") // Fixed Headers
                .delete(baseUrlOfSut + "/media/medias/995")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Media 995 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
