/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-09T00:49:52.002239055Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 6
 * <br>
*  Used time: 0h 2m 7s
 * <br>
*  Needed budget for current results: 93%
 * <br>
*  This file contains test cases that represent successful calls.
*/
public class EvoMaster_promotion_customer_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/promotion/storefront/promotions/updateUsage
    */
    @Test @Timeout(60)
    public void test_0_postOnUpdateUsageReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzMwMTc1NjIsImlhdCI6MTc3MzAxNzI2MiwianRpIjoiMzE4OWRhZjgtOGM0My00NjU1LTg1NGQtNThhNTFkMjg2NmY2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjVhM2M3Zjc5LWNkOTYtNDc1Mi1iMjYyLWRhYTg3MGYyMmI0OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.eadkYyrxJlXk6hGzObU-MtzIwaR7RMIV8Di2fVO2N0aJENsWCzxF0jhFvh4jdfAHp8SxRuyaJmCnZUPy03jfS00JfwWOSl-vmf2lSH10YiTbnEWCb_vMrQfQq6L1VL5tOfOzTStrN6c-JIVNsGE5axZlgx0W7HOXWCFoM1ubFefUb53wpoDHzacqMXzYWJKKmVckTJ5Q2n2YV7giQhK2_iXQAgSgLxelb2uZJTc5vsX4Cw54rHo48-JsJejNoM-T0kW2X7Gb1mpFwS4ABVtcDwTem8LjwZnY-RScdrL-_hhhJ9vLllxlLi-0B9zeO6DIhhyJo_bctIjrgjTuWxCzyg") // Fixed Headers
                .contentType("application/json")
                .body(" [] ")
                .post(baseUrlOfSut + "/promotion/storefront/promotions/updateUsage")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
