/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-04-07T01:06:36.931735441Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 4
 * <br>
*  Used time: 0h 1m 57s
 * <br>
*  Needed budget for current results: 69%
 * <br>
*  This file contains test cases that represent successful calls.
*/
public class EvoMaster_customer_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/customer/storefront/user-address
    */
    @Test @Timeout(60)
    public void test_0_getOnUser_addressReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzU1MjQxNzcsImlhdCI6MTc3NTUyMzg3NywianRpIjoiOWM2Zjk4M2UtOTQ3Mi00ZTg3LTkzNjktOTFhYjVlNDExYjEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjM0NWFlZTcxLTAxNTUtNDYwMy04NDkyLWU0OGVlYjlhM2RjMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.AWl-fHwzuvQT_psax5MQSi0MtXXYnT9J7x5NEepcQxLY4axkFKEUuwJvZvA5xSXlotjIl-hjCcefJqzzQIfWZPLHaSKtHsgwb8dgFC2SfBpgwCuMMqLsYEpeCNwitkKBhcqQBHs_aV2Gn3Db32BFzeBkBN4J1eNE_zs4wf1_4xZ-yngYKqbl46D4EUQORXwoICjvNODylxF8hJUB1AimAcrDtLENwzSXVl218qLKjDDz_pIBiUpKQr7dcaO9LdrgGQ7X1Mo9hmOy0-6ddub0lYVrmjtQoUTK0KyjTU_3B10tIZxfNo_rbvXu3iq2Sh_2Sj7helLUeAGyBM-j4dWi5A") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
